import { and, eq } from "drizzle-orm";
import { clientesTable, db, municipiosTable } from "../index.js";

async function getMunicipioId(nome: string, uf: string): Promise<number | null> {
  const result = await db
    .select({ id: municipiosTable.id })
    .from(municipiosTable)
    .where(and(eq(municipiosTable.nome, nome), eq(municipiosTable.uf, uf)))
    .limit(1);
  return result[0]?.id ?? null;
}

const clientes = [
  {
    nomeRazaoSocial: "Grafica Agetra Ltda",
    nomeFantasia: "Agetra",
    nomeInterno: "Agetra",
    juridica: true,
    cnpjCpf: "72330772000100",
    inscrEstadual: "0850022541",
    inscrMunicipal: "42.085/004-2",
    telefone: "(54)3242-1679",
    logradouro: "Rua Buarque de Macedo",
    numero: "2120",
    complemento: "Nulo",
    bairro: "Sao Cristovao",
    cep: "95320-000",
    emailNfse: "orcamento@agetra.com.br;orcamento3@agetra.com.br",
    nomeContato: "",
    emailContato: "orcamento@agetra.com.br;orcamento3@agetra.com.br",
    emailAprovaDemonstrativo: "orcamento@agetra.com.br;orcamento3@agetra.com.br",
    emailInformaProdutoEmbalado: "orcamento@agetra.com.br;orcamento3@agetra.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/GraficaAgetra",
    diretorioDemonstrativo: "/Demostrativo/GraficaAgetra",
    prazoPagamento:  14 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Nova Prata",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Imobiliaria Bassanesi Ltda",
    nomeFantasia: "Bassanesi",
    nomeInterno: "Bassanesi",
    juridica: true,
    cnpjCpf: "89278683000157",
    inscrEstadual: "Nulo",
    inscrMunicipal: "15014",
    telefone: "(54)3220-1951",
    logradouro: "Av. Julio de Castilhos",
    numero: "1399",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95010-003",
    emailNfse: "luciana@bassanesi.com.br",
    nomeContato: "",
    emailContato: "luciana@bassanesi.com.br",
    emailAprovaDemonstrativo: "luciana@bassanesi.com.br",
    emailInformaProdutoEmbalado: "luciana@bassanesi.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Bassanesi",
    diretorioDemonstrativo: "/Demostrativo/Bassanesi",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Imobiliaria Bento Alves Ltda",
    nomeFantasia: "Bento Alves",
    nomeInterno: "Bento Alves",
    juridica: true,
    cnpjCpf: "88659206000179",
    inscrEstadual: "Nulo",
    inscrMunicipal: "37616",
    telefone: "(54)3209-6400",
    logradouro: "Av. Julio de Castilhos",
    numero: "1494",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95010-000",
    emailNfse: "financeiro@bentoalves.com.br",
    nomeContato: "",
    emailContato: "financeiro@bentoalves.com.br",
    emailAprovaDemonstrativo: "financeiro@bentoalves.com.br",
    emailInformaProdutoEmbalado: "financeiro@bentoalves.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/BentoAlves",
    diretorioDemonstrativo: "/Demostrativo/BentoAlves",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "JD Comercio, Importacao, Representacoes e Transportes Ltda",
    nomeFantasia: "Boccati",
    nomeInterno: "Boccati",
    juridica: true,
    cnpjCpf: "89371561000100",
    inscrEstadual: "0290114012",
    inscrMunicipal: "38395",
    telefone: "(54)3224-9900",
    logradouro: "Rua Antonio Ribeiro Mendes",
    numero: "2043",
    complemento: "Nulo",
    bairro: "Santa Catarina",
    cep: "95032-600",
    emailNfse: "nf@boccati.com.br;tatiana@boccati.com.br",
    nomeContato: "",
    emailContato: "nf@boccati.com.br;tatiana@boccati.com.br",
    emailAprovaDemonstrativo: "nf@boccati.com.br;tatiana@boccati.com.br",
    emailInformaProdutoEmbalado: "nf@boccati.com.br;tatiana@boccati.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Boccati",
    diretorioDemonstrativo: "/Demostrativo/Boccati",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Imobiliaria Cadore Ltda",
    nomeFantasia: "Cadore",
    nomeInterno: "Cadore",
    juridica: true,
    cnpjCpf: "03744757000188",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3028-0390",
    logradouro: "Rua Os Dezoito do Forte",
    numero: "1622",
    complemento: "Nulo",
    bairro: "SaoPelegrino",
    cep: "95020-472",
    emailNfse: "alugueis@imobiliariacadore.com.br",
    nomeContato: "",
    emailContato: "alugueis@imobiliariacadore.com.br",
    emailAprovaDemonstrativo: "alugueis@imobiliariacadore.com.br",
    emailInformaProdutoEmbalado: "alugueis@imobiliariacadore.com.br",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Cadore",
    diretorioDemonstrativo: "/Demostrativo/Cadore",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Castertech Fundicao e Tecnologia Ltda",
    nomeFantasia: "Castertech",
    nomeInterno: "Castertech",
    juridica: true,
    cnpjCpf: "08304706000159",
    inscrEstadual: "0290458889",
    inscrMunicipal: "94026",
    telefone: "(54)3239-3600",
    logradouro: "Avenida Abramo Randon",
    numero: "770",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Folha",
    diretorioDemonstrativo: "/Demostrativo/Randon/Folha",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Camara de Dirigentes Lojistas de Caxias do Sul",
    nomeFantasia: "CDL - Caxias",
    nomeInterno: "CDL - Caxias",
    juridica: true,
    cnpjCpf: "88639281000178",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3209-9977",
    logradouro: "Rua Sinimbu",
    numero: "1415",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-001",
    emailNfse: "financeiro@cdlcaxias.com.br;taina.pradella@cdlcaxias.com.br",
    nomeContato: "",
    emailContato: "financeiro@cdlcaxias.com.br;taina.pradella@cdlcaxias.com.br",
    emailAprovaDemonstrativo: "financeiro@cdlcaxias.com.br;taina.pradella@cdlcaxias.com.br",
    emailInformaProdutoEmbalado: "financeiro@cdlcaxias.com.br;taina.pradella@cdlcaxias.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/CDL-Caxias/Boleto",
    diretorioDemonstrativo: "/Demostrativo/CDL-Caxias/Boleto",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Cirna Industria de Plasticos e Moldes Ltda",
    nomeFantasia: "Cirna",
    nomeInterno: "Cirna",
    juridica: true,
    cnpjCpf: "87826202000175",
    inscrEstadual: "0290039843",
    inscrMunicipal: "Nulo",
    telefone: "(54)3212-1644",
    logradouro: "Rua Padre Raul Accorsi",
    numero: "900",
    complemento: "Nulo",
    bairro: "De Zorzi",
    cep: "95074-300",
    emailNfse: "nfe@cirna.com.br;andressa@cirna.com.br",
    nomeContato: "",
    emailContato: "nfe@cirna.com.br;andressa@cirna.com.br",
    emailAprovaDemonstrativo: "nfe@cirna.com.br;andressa@cirna.com.br",
    emailInformaProdutoEmbalado: "nfe@cirna.com.br;andressa@cirna.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Cirna",
    diretorioDemonstrativo: "/Demostrativo/Cirna",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Cooperativa de Economia e Credito Mutuo dos Empregados das Empresas Randon",
    nomeFantasia: "Cooperando",
    nomeInterno: "Cooperando",
    juridica: true,
    cnpjCpf: "89280960000166",
    inscrEstadual: "Nulo",
    inscrMunicipal: "73977",
    telefone: "(54)3239-4496",
    logradouro: "Avenida Abramo Randon",
    numero: "770",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "poliana.zini@randon.com.br",
    nomeContato: "",
    emailContato: "poliana.zini@randon.com.br",
    emailAprovaDemonstrativo: "poliana.zini@randon.com.br",
    emailInformaProdutoEmbalado: "poliana.zini@randon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Cooperando",
    diretorioDemonstrativo: "/Demostrativo/Randon/Cooperando",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Dzainer Produtos Plasticos Ltda",
    nomeFantasia: "Dzainer",
    nomeInterno: "Dzainer",
    juridica: true,
    cnpjCpf: "73960874000164",
    inscrEstadual: "0290252741",
    inscrMunicipal: "32019",
    telefone: "(54)2992-8700",
    logradouro: "Rua dos Tangaras",
    numero: "1637",
    complemento: "Caixa Postal 8034",
    bairro: "Santa Fe",
    cep: "95047-570",
    emailNfse: "recebimento.nfe@dzainer.com.br",
    nomeContato: "",
    emailContato: "recebimento.nfe@dzainer.com.br",
    emailAprovaDemonstrativo: "recebimento.nfe@dzainer.com.br",
    emailInformaProdutoEmbalado: "recebimento.nfe@dzainer.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Dzainer",
    diretorioDemonstrativo: "/Demostrativo/Dzainer",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Farina S.A. Componentes Automotivos",
    nomeFantasia: "Farina",
    nomeInterno: "Farina",
    juridica: true,
    cnpjCpf: "87546636000111",
    inscrEstadual: "0100000770",
    inscrMunicipal: "Nulo",
    telefone: "(54)2102-8622",
    logradouro: "Rua Cavalheiro Jose Farina",
    numero: "215",
    complemento: "Nulo",
    bairro: "Licorsul",
    cep: "95703-006",
    emailNfse: "clarisse@farina.com.br;grasiela.rodighero@farina.com.br",
    nomeContato: "",
    emailContato: "clarisse@farina.com.br;grasiela.rodighero@farina.com.br",
    emailAprovaDemonstrativo: "clarisse@farina.com.br;grasiela.rodighero@farina.com.br",
    emailInformaProdutoEmbalado: "clarisse@farina.com.br;grasiela.rodighero@farina.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Farina",
    diretorioDemonstrativo: "/Demostrativo/Farina",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Bento Gonçalves",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Federacao dos Hospitais e Estabelecimentos Servicos Saude do RS",
    nomeFantasia: "Fehosul",
    nomeInterno: "Fehosul",
    juridica: true,
    cnpjCpf: "93246940000146",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(51)3234-1100",
    logradouro: "Rua Corte Real",
    numero: "133",
    complemento: "Nulo",
    bairro: "PetrOpolis",
    cep: "90630-080",
    emailNfse: "financeiro@fehosul.gov.br",
    nomeContato: "",
    emailContato: "financeiro@fehosul.gov.br",
    emailAprovaDemonstrativo: "financeiro@fehosul.gov.br",
    emailInformaProdutoEmbalado: "financeiro@fehosul.gov.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/FEHOSUL",
    diretorioDemonstrativo: "/Demostrativo/FEHOSUL",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Porto Alegre",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Fox Administradora de Condominios Ltda",
    nomeFantasia: "Fox",
    nomeInterno: "Fox",
    juridica: true,
    cnpjCpf: "07272047000153",
    inscrEstadual: "Nulo",
    inscrMunicipal: "86431",
    telefone: "(54)3027-4020",
    logradouro: "Rua Pedro Tomasi",
    numero: "937",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95084-320",
    emailNfse: "atendimento@foxcondominios.com.br",
    nomeContato: "",
    emailContato: "atendimento@foxcondominios.com.br",
    emailAprovaDemonstrativo: "atendimento@foxcondominios.com.br",
    emailInformaProdutoEmbalado: "atendimento@foxcondominios.com.br",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/FoxAdmCond",
    diretorioDemonstrativo: "/Demostrativo/FoxAdmCond",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Fras-Le S/A",
    nomeFantasia: "Fras-Le",
    nomeInterno: "Fras-Le",
    juridica: true,
    cnpjCpf: "88610126000129",
    inscrEstadual: "0290014735",
    inscrMunicipal: "17007",
    telefone: "(54)3239-1809",
    logradouro: "Rodovia RS 122 Km 66,1",
    numero: "10945",
    complemento: "Nulo",
    bairro: "Forqueta",
    cep: "95115-550",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Fras-le",
    diretorioDemonstrativo: "/Demostrativo/Randon/Fras-le",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Administradora de Imoveis Fulcher Ltda",
    nomeFantasia: "Fulcher",
    nomeInterno: "Fulcher",
    juridica: true,
    cnpjCpf: "93640480000136",
    inscrEstadual: "Nulo",
    inscrMunicipal: "13177",
    telefone: "(54)3214-2727",
    logradouro: "Avenida Julio de Castilhos",
    numero: "1183",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95010-003",
    emailNfse: "financeiro@fulcherimoveis.com.br",
    nomeContato: "",
    emailContato: "financeiro@fulcherimoveis.com.br",
    emailAprovaDemonstrativo: "financeiro@fulcherimoveis.com.br",
    emailInformaProdutoEmbalado: "financeiro@fulcherimoveis.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Fulcher",
    diretorioDemonstrativo: "/Demostrativo/Fulcher",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "G Paniz Ind de Equip P/ Alimentacao Ltda",
    nomeFantasia: "G Paniz",
    nomeInterno: "G Paniz",
    juridica: true,
    cnpjCpf: "90771833000149",
    inscrEstadual: "0290084474",
    inscrMunicipal: "12462",
    telefone: "(54)2101-2400",
    logradouro: "Rua Adolfo Randazzo",
    numero: "2010",
    complemento: "Caixa Postal 8012",
    bairro: "Vila Maestra",
    cep: "95046-800",
    emailNfse: "fiscal01@gpaniz.com.br;eliamara.lazzaretti@gpaniz.com.br",
    nomeContato: "",
    emailContato: "fiscal01@gpaniz.com.br;eliamara.lazzaretti@gpaniz.com.br",
    emailAprovaDemonstrativo: "fiscal01@gpaniz.com.br;eliamara.lazzaretti@gpaniz.com.br",
    emailInformaProdutoEmbalado: "fiscal01@gpaniz.com.br;eliamara.lazzaretti@gpaniz.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Gpaniz",
    diretorioDemonstrativo: "/Demostrativo/Gpaniz",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Grazziotin Negocios Imobiliarios Ltda",
    nomeFantasia: "Grazziotin",
    nomeInterno: "Grazziotin",
    juridica: true,
    cnpjCpf: "92514801000193",
    inscrEstadual: "Nulo",
    inscrMunicipal: "4572",
    telefone: "(54)3028-1515",
    logradouro: "Rua Ernesto Alves",
    numero: "1545",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-360",
    emailNfse: "tania@imobiliariagrazziotin.com.br",
    nomeContato: "",
    emailContato: "tania@imobiliariagrazziotin.com.br",
    emailAprovaDemonstrativo: "tania@imobiliariagrazziotin.com.br",
    emailInformaProdutoEmbalado: "tania@imobiliariagrazziotin.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Grazziotin",
    diretorioDemonstrativo: "/Demostrativo/Grazziotin",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Hidro Jet Equipamentos Hidraulicos Ltda",
    nomeFantasia: "Hidrojet",
    nomeInterno: "Hidrojet",
    juridica: true,
    cnpjCpf: "90952052000150",
    inscrEstadual: "0470018640",
    inscrMunicipal: "42105002",
    telefone: "(51)3637-4000",
    logradouro: "RS 452 Km 2",
    numero: "3101",
    complemento: "Nulo",
    bairro: "Bom Fim",
    cep: "95770-000",
    emailNfse: "aline.carneiro@hidrojet.ind.br;financeiro@hidrojet.ind.br",
    nomeContato: "",
    emailContato: "aline.carneiro@hidrojet.ind.br;financeiro@hidrojet.ind.br",
    emailAprovaDemonstrativo: "aline.carneiro@hidrojet.ind.br;financeiro@hidrojet.ind.br",
    emailInformaProdutoEmbalado: "aline.carneiro@hidrojet.ind.br;financeiro@hidrojet.ind.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Hidrojet",
    diretorioDemonstrativo: "/Demostrativo/Hidrojet",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Feliz",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Hospital Beneficente Sao Carlos",
    nomeFantasia: "HBSC",
    nomeInterno: "HBSC",
    juridica: true,
    cnpjCpf: "89847370000172",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3261-8787",
    logradouro: "Rua da Republica",
    numero: "51",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95170-476",
    emailNfse: "luciane@hbsc.com.br",
    nomeContato: "",
    emailContato: "luciane@hbsc.com.br",
    emailAprovaDemonstrativo: "luciane@hbsc.com.br",
    emailInformaProdutoEmbalado: "luciane@hbsc.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/HBSC",
    diretorioDemonstrativo: "/Demostrativo/HBSC",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Farroupilha",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Jost Brasil Sistemas Automotivos Ltda",
    nomeFantasia: "Jost",
    nomeInterno: "Jost",
    juridica: true,
    cnpjCpf: "00843966000190",
    inscrEstadual: "0290282713",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2000",
    logradouro: "Avenida Abramo Randon",
    numero: "1200",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "nfeser_jost@randon.com.br",
    nomeContato: "",
    emailContato: "nfeser_jost@randon.com.br",
    emailAprovaDemonstrativo: "nfeser_jost@randon.com.br",
    emailInformaProdutoEmbalado: "nfeser_jost@randon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Jost",
    diretorioDemonstrativo: "/Demostrativo/Randon/Jost",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Clube Juvenil",
    nomeFantasia: "Juvenil",
    nomeInterno: "Juvenil",
    juridica: true,
    cnpjCpf: "88664305000149",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3223-5866",
    logradouro: "Avenida Julio de Castilhos",
    numero: "1677",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95010-002",
    emailNfse: "gerenciadm@clubejuvenilcaxias.com.br;financeiro@clubejuvenilcaxias.com.br",
    nomeContato: "",
    emailContato: "gerenciadm@clubejuvenilcaxias.com.br;financeiro@clubejuvenilcaxias.com.br",
    emailAprovaDemonstrativo: "gerenciadm@clubejuvenilcaxias.com.br;financeiro@clubejuvenilcaxias.com.br",
    emailInformaProdutoEmbalado: "gerenciadm@clubejuvenilcaxias.com.br;financeiro@clubejuvenilcaxias.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Juvenil",
    diretorioDemonstrativo: "/Demostrativo/Juvenil",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Lupatech S.A.",
    nomeFantasia: "Lupatech",
    nomeInterno: "Lupatech",
    juridica: true,
    cnpjCpf: "89463822000112",
    inscrEstadual: "0290011526",
    inscrMunicipal: "Nulo",
    telefone: "(11)3309-9000",
    logradouro: "Rua Dalton Lahm dos Reis",
    numero: "201",
    complemento: "Nulo",
    bairro: "Distrito Industrial",
    cep: "95112-090",
    emailNfse: "luciana.parise@lupatech.com.br",
    nomeContato: "",
    emailContato: "luciana.parise@lupatech.com.br",
    emailAprovaDemonstrativo: "luciana.parise@lupatech.com.br",
    emailInformaProdutoEmbalado: "luciana.parise@lupatech.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LUPATECH",
    diretorioDemonstrativo: "/Demostrativo/LUPATECH",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Mipel Industria e Comercio de Valvulas Ltda",
    nomeFantasia: "Mipel Sul",
    nomeInterno: "Mipel Sul",
    juridica: true,
    cnpjCpf: "07743815000100",
    inscrEstadual: "1570042010",
    inscrMunicipal: "Nulo",
    telefone: "(54)2992-7000",
    logradouro: "Rua Casemiro Ecco",
    numero: "417",
    complemento: "Nulo",
    bairro: "Vila Azul",
    cep: "95330-000",
    emailNfse: "luciana.parise@lupatech.com.br",
    nomeContato: "",
    emailContato: "luciana.parise@lupatech.com.br",
    emailAprovaDemonstrativo: "luciana.parise@lupatech.com.br",
    emailInformaProdutoEmbalado: "luciana.parise@lupatech.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LUPATECH",
    diretorioDemonstrativo: "/Demostrativo/LUPATECH",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Veranópolis",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Mipel Industria e Comercio de Valvulas Ltda",
    nomeFantasia: "Microfusao",
    nomeInterno: "Microfusao",
    juridica: true,
    cnpjCpf: "07743815000290",
    inscrEstadual: "1570045370",
    inscrMunicipal: "Nulo",
    telefone: "(54)2992-7000",
    logradouro: "Rua Casemiro Ecco",
    numero: "421",
    complemento: "Nulo",
    bairro: "Vila Azul",
    cep: "95330-000",
    emailNfse: "nfe.veranopolis@lupatech.com.br;markele.remor@lupatech.com.br",
    nomeContato: "",
    emailContato: "nfe.veranopolis@lupatech.com.br;markele.remor@lupatech.com.br",
    emailAprovaDemonstrativo: "nfe.veranopolis@lupatech.com.br;markele.remor@lupatech.com.br",
    emailInformaProdutoEmbalado: "nfe.veranopolis@lupatech.com.br;markele.remor@lupatech.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LUPATECH",
    diretorioDemonstrativo: "/Demostrativo/LUPATECH",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Veranópolis",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Lupatech S.A.",
    nomeFantasia: "Valmicro",
    nomeInterno: "Valmicro",
    juridica: true,
    cnpjCpf: "89463822001003",
    inscrEstadual: "1570047674",
    inscrMunicipal: "Nulo",
    telefone: "(54)2992-7000",
    logradouro: "Rua Casemiro Ecco",
    numero: "415",
    complemento: "Nulo",
    bairro: "Industrial",
    cep: "95330-000",
    emailNfse: "nfe.veranopolis@lupatech.com.br;nfe@lupatech.com.br;markele.remor@lupatech.com.br",
    nomeContato: "",
    emailContato: "nfe.veranopolis@lupatech.com.br;nfe@lupatech.com.br;markele.remor@lupatech.com.br",
    emailAprovaDemonstrativo: "nfe.veranopolis@lupatech.com.br;nfe@lupatech.com.br;markele.remor@lupatech.com.br",
    emailInformaProdutoEmbalado: "nfe.veranopolis@lupatech.com.br;nfe@lupatech.com.br;markele.remor@lupatech.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LUPATECH",
    diretorioDemonstrativo: "/Demostrativo/LUPATECH",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Veranópolis",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Marcopolo S.A",
    nomeFantasia: "Marcopolo",
    nomeInterno: "Marcopolo",
    juridica: true,
    cnpjCpf: "88611835000803",
    inscrEstadual: "0290086299",
    inscrMunicipal: "Nulo",
    telefone: "(54)2101-4221",
    logradouro: "Avenida Rio Branco",
    numero: "4889",
    complemento: "Nulo",
    bairro: "Ana Rech",
    cep: "95060-650",
    emailNfse: "juliana.souza@marcopolo.com.br;bruno.santo@marcopolo.com.br;leandro.cavalin@marcopolo.com.br",
    nomeContato: "",
    emailContato: "juliana.souza@marcopolo.com.br;bruno.santo@marcopolo.com.br;leandro.cavalin@marcopolo.com.br",
    emailAprovaDemonstrativo: "juliana.souza@marcopolo.com.br;bruno.santo@marcopolo.com.br;leandro.cavalin@marcopolo.com.br",
    emailInformaProdutoEmbalado: "juliana.souza@marcopolo.com.br;bruno.santo@marcopolo.com.br;leandro.cavalin@marcopolo.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Marcopolo",
    diretorioDemonstrativo: "/Demostrativo/Marcopolo",
    prazoPagamento:  30 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Master Sistemas Automotivos Ltda",
    nomeFantasia: "Master",
    nomeInterno: "Master",
    juridica: true,
    cnpjCpf: "90852914000173",
    inscrEstadual: "0290137551",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2000",
    logradouro: "Rua Atilio Andreazza",
    numero: "3520",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95052-070",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Master",
    diretorioDemonstrativo: "/Demostrativo/Randon/Master",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Microinox - Fundicao de Precisao e Usinagem Ltda",
    nomeFantasia: "Microinox",
    nomeInterno: "Microinox",
    juridica: true,
    cnpjCpf: "13785854000172",
    inscrEstadual: "0290542677",
    inscrMunicipal: "Nulo",
    telefone: "(54)3022-2590",
    logradouro: "Rua Gerson Andreis",
    numero: "892",
    complemento: "Nulo",
    bairro: "Distrito Industrial",
    cep: "95112-130",
    emailNfse: "nfe.microinox@microinox.com.br",
    nomeContato: "",
    emailContato: "nfe.microinox@microinox.com.br",
    emailAprovaDemonstrativo: "nfe.microinox@microinox.com.br",
    emailInformaProdutoEmbalado: "nfe.microinox@microinox.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Hidrojet",
    diretorioDemonstrativo: "/Demostrativo/Hidrojet",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Imobiliaria Nichele Ltda",
    nomeFantasia: "Nichele",
    nomeInterno: "Nichele",
    juridica: true,
    cnpjCpf: "88655113000176",
    inscrEstadual: "Nulo",
    inscrMunicipal: "29422",
    telefone: "(54)3289-2900",
    logradouro: "Rua Visconde de Pelotas",
    numero: "381",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-180",
    emailNfse: "marta@nicheleimoveis.com.br",
    nomeContato: "",
    emailContato: "marta@nicheleimoveis.com.br",
    emailAprovaDemonstrativo: "marta@nicheleimoveis.com.br",
    emailInformaProdutoEmbalado: "marta@nicheleimoveis.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Nichele",
    diretorioDemonstrativo: "/Demostrativo/Nichele",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Opusadmin Administradora de Condominios Ltda",
    nomeFantasia: "Opus",
    nomeInterno: "Opus",
    juridica: true,
    cnpjCpf: "07062800000186",
    inscrEstadual: "Nulo",
    inscrMunicipal: "85382",
    telefone: "(54)3228-6619",
    logradouro: "Rua Os Dezoito do Forte",
    numero: "422",
    complemento: "Sala 408",
    bairro: "Nossa Senhora de Lourdes",
    cep: "95020-472",
    emailNfse: "opus@opusadmin.com.br",
    nomeContato: "",
    emailContato: "opus@opusadmin.com.br",
    emailAprovaDemonstrativo: "opus@opusadmin.com.br",
    emailInformaProdutoEmbalado: "opus@opusadmin.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Opus",
    diretorioDemonstrativo: "/Demostrativo/Opus",
    prazoPagamento:  14 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Panaser S.A. Beneficiamento de Acos",
    nomeFantasia: "Panaser",
    nomeInterno: "Panaser",
    juridica: true,
    cnpjCpf: "15511094000130",
    inscrEstadual: "0450097374",
    inscrMunicipal: "16901",
    telefone: "(54)3906-8900",
    logradouro: "Estrada RST 453, Km 114+960",
    numero: "6605",
    complemento: "Nulo",
    bairro: "Linha Vicentina",
    cep: "95172-090",
    emailNfse: "nfe@panaser.com.br",
    nomeContato: "",
    emailContato: "nfe@panaser.com.br",
    emailAprovaDemonstrativo: "nfe@panaser.com.br",
    emailInformaProdutoEmbalado: "nfe@panaser.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Panatlantica",
    diretorioDemonstrativo: "/Demostrativo/Panatlantica",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Farroupilha",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Panatlantica Industria e Comercio de Tubos S.A.",
    nomeFantasia: "Panatlantica",
    nomeInterno: "Panatlantica",
    juridica: true,
    cnpjCpf: "03684007000168",
    inscrEstadual: "0290423937",
    inscrMunicipal: "84531",
    telefone: "(54)3211-8525",
    logradouro: "Rodovia RST 453, Km 80",
    numero: "32973",
    complemento: "Nulo",
    bairro: "Nossa Senhora da Saude",
    cep: "95042-190",
    emailNfse: "nfservico@panatlanticatubos.com.br;recursos@panatlanticatubos.com.br",
    nomeContato: "",
    emailContato: "nfservico@panatlanticatubos.com.br;recursos@panatlanticatubos.com.br",
    emailAprovaDemonstrativo: "nfservico@panatlanticatubos.com.br;recursos@panatlanticatubos.com.br",
    emailInformaProdutoEmbalado: "nfservico@panatlanticatubos.com.br;recursos@panatlanticatubos.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Panatlantica",
    diretorioDemonstrativo: "/Demostrativo/Panatlantica",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Municipio de Caxias do Sul",
    nomeFantasia: "PM Caxias",
    nomeInterno: "PM Caxias",
    juridica: true,
    cnpjCpf: "88830609000139",
    inscrEstadual: "Nulo",
    inscrMunicipal: "71469",
    telefone: "(54)3218-6000",
    logradouro: "Rua Alfredo Chaves",
    numero: "1333",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-460",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/PrefCaxias",
    diretorioDemonstrativo: "/Demostrativo/PrefCaxias",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Prolar Imoveis Administracao e Corretagem Ltda",
    nomeFantasia: "Prolar",
    nomeInterno: "Prolar",
    juridica: true,
    cnpjCpf: "87506283000126",
    inscrEstadual: "Nulo",
    inscrMunicipal: "10501",
    telefone: "(54)3026-8999",
    logradouro: "Avenida Julio de Castilhos",
    numero: "657",
    complemento: "Nulo",
    bairro: "Nossa Senhora de Lourdes",
    cep: "95010-003",
    emailNfse: "liliana@prolar.imb.br;evandro@prolar.imb.br",
    nomeContato: "",
    emailContato: "liliana@prolar.imb.br;evandro@prolar.imb.br",
    emailAprovaDemonstrativo: "liliana@prolar.imb.br;evandro@prolar.imb.br",
    emailInformaProdutoEmbalado: "liliana@prolar.imb.br;evandro@prolar.imb.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/PROLAR",
    diretorioDemonstrativo: "/Demostrativo/PROLAR",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Randon S/A Implementos e Participacoes",
    nomeFantasia: "Brantech",
    nomeInterno: "Brantech",
    juridica: true,
    cnpjCpf: "89086144001007",
    inscrEstadual: "257313087",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2000",
    logradouro: "Rodovia SC 459, km 143,7",
    numero: "Nulo",
    complemento: "Nulo",
    bairro: "Trecho Chapeco, Guatambu",
    cep: "89809-970",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Brantech",
    diretorioDemonstrativo: "/Demostrativo/Brantech",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Chapecó",
    municipioUF: "SC",
  },
  {
    nomeRazaoSocial: "Randon S/A Implementos e Participacoes",
    nomeFantasia: "Randon Cx - Implem",
    nomeInterno: "Randon Cx - Implem",
    juridica: true,
    cnpjCpf: "89086144000116",
    inscrEstadual: "0290400465",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2000",
    logradouro: "Avenida Abramo Randon",
    numero: "770",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Folha",
    diretorioDemonstrativo: "/Demostrativo/Randon/Folha",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Randon S/A Implementos e Participacoes",
    nomeFantasia: "Randon Cx - Holding",
    nomeInterno: "Randon Cx - Holding",
    juridica: true,
    cnpjCpf: "89086144001198",
    inscrEstadual: "0290400465",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2000",
    logradouro: "Avenida Abramo Randon",
    numero: "770",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Folha",
    diretorioDemonstrativo: "/Demostrativo/Randon/Folha",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Randon Administradora de Consorcios Ltda",
    nomeFantasia: "Racon",
    nomeInterno: "Racon",
    juridica: true,
    cnpjCpf: "91108027000158",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-2738",
    logradouro: "Rua Atilio Andreazza",
    numero: "3480",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95052-070",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Folha",
    diretorioDemonstrativo: "/Demostrativo/Randon/Folha",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Real Center Materiais e Equipamentos Eletricos Ltda",
    nomeFantasia: "Real Center",
    nomeInterno: "Real Center",
    juridica: true,
    cnpjCpf: "93364974000135",
    inscrEstadual: "0290195535",
    inscrMunicipal: "10402",
    telefone: "(54)3534-4400",
    logradouro: "Avenida Rubem Bento Alves",
    numero: "3167",
    complemento: "Nulo",
    bairro: "Santa Catarina",
    cep: "95032-440",
    emailNfse: "fiscal@realcenter.com.br",
    nomeContato: "",
    emailContato: "fiscal@realcenter.com.br",
    emailAprovaDemonstrativo: "fiscal@realcenter.com.br",
    emailInformaProdutoEmbalado: "fiscal@realcenter.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/RealCenter",
    diretorioDemonstrativo: "/Demostrativo/RealCenter",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Resulthado Solucoes A Condominios Ltda",
    nomeFantasia: "Resulthado",
    nomeInterno: "Resulthado",
    juridica: true,
    cnpjCpf: "09549273000164",
    inscrEstadual: "Nulo",
    inscrMunicipal: "101650",
    telefone: "(54)3028-8616",
    logradouro: "Rua Bento Gonçalves",
    numero: "1282",
    complemento: "Sala 05",
    bairro: "Centro",
    cep: "95020-412",
    emailNfse: "resulthado@resulthado.com.br",
    nomeContato: "",
    emailContato: "resulthado@resulthado.com.br",
    emailAprovaDemonstrativo: "resulthado@resulthado.com.br",
    emailInformaProdutoEmbalado: "resulthado@resulthado.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Resulthado",
    diretorioDemonstrativo: "/Demostrativo/Resulthado",
    prazoPagamento:  14 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Associacao dos Moradores do Jardim Da Lagoa",
    nomeFantasia: "AMJL",
    nomeInterno: "AMJL",
    juridica: true,
    cnpjCpf: "90256579000140",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(51)3592-2646",
    logradouro: "Rua da Margem",
    numero: "Nulo",
    complemento: "S/N",
    bairro: "Jardim da Lagoa",
    cep: "95520-000",
    emailNfse: "sindisys.sle@gmail.com;guilha01@hotmail.com",
    nomeContato: "",
    emailContato: "sindisys.sle@gmail.com;guilha01@hotmail.com",
    emailAprovaDemonstrativo: "sindisys.sle@gmail.com;guilha01@hotmail.com",
    emailInformaProdutoEmbalado: "sindisys.sle@gmail.com;guilha01@hotmail.com",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/SindiLojas-SLeo/Condominio",
    diretorioDemonstrativo: "/Demostrativo/SindiLojas-SLeo/Condominio",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Osório",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Sindicato do Comercio Varejista de SaoLeopoldo",
    nomeFantasia: "Sindilojas - Sao Leo",
    nomeInterno: "Sindilojas - Sao Leo",
    juridica: true,
    cnpjCpf: "91100339000115",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(51)3592-2646",
    logradouro: "Rua Jose Bonifacio",
    numero: "1009",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "93010-180",
    emailNfse: "sindileo@sindileo.com.br",
    nomeContato: "",
    emailContato: "sindileo@sindileo.com.br",
    emailAprovaDemonstrativo: "sindileo@sindileo.com.br",
    emailInformaProdutoEmbalado: "sindileo@sindileo.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/SindiLojas-Sleo",
    diretorioDemonstrativo: "/Demostrativo/SindiLojas-Sleo",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "São Leopoldo",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Sind. dos Odontologistas de Caxias do Sul",
    nomeFantasia: "Sindiodonto",
    nomeInterno: "Sindiodonto",
    juridica: true,
    cnpjCpf: "90773326000144",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3223-5300",
    logradouro: "Av. Julio de Castilhos",
    numero: "1188",
    complemento: "Sala 42",
    bairro: "Nossa Senhora de Lourdes",
    cep: "95010-003",
    emailNfse: "contato@sindiodontoserra.com.br",
    nomeContato: "",
    emailContato: "contato@sindiodontoserra.com.br",
    emailAprovaDemonstrativo: "contato@sindiodontoserra.com.br",
    emailInformaProdutoEmbalado: "contato@sindiodontoserra.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/SindioOdonto-CX",
    diretorioDemonstrativo: "/Demostrativo/SindioOdonto-CX",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "So Condominios Administradora Ltda",
    nomeFantasia: "So Condominios",
    nomeInterno: "So Condominios",
    juridica: true,
    cnpjCpf: "03286644000186",
    inscrEstadual: "Nulo",
    inscrMunicipal: "68272",
    telefone: "(54)3221-5566",
    logradouro: "Rua Os Dezoito do Forte",
    numero: "1344",
    complemento: "Sala 21 e 22",
    bairro: "SaoPelegrino",
    cep: "95020-472",
    emailNfse: "financeiro@socondominios.srv.br",
    nomeContato: "",
    emailContato: "financeiro@socondominios.srv.br",
    emailAprovaDemonstrativo: "financeiro@socondominios.srv.br",
    emailInformaProdutoEmbalado: "financeiro@socondominios.srv.br",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/SoCondominios",
    diretorioDemonstrativo: "/Demostrativo/SoCondominios",
    prazoPagamento:  4 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Solucao Servicos para Condominios Ltda Me",
    nomeFantasia: "Solucao",
    nomeInterno: "Solucao",
    juridica: true,
    cnpjCpf: "03728366000170",
    inscrEstadual: "Nulo",
    inscrMunicipal: "71831",
    telefone: "(54)3222-6377",
    logradouro: "Rua Tronca",
    numero: "1959",
    complemento: "Sala 2 - terreo",
    bairro: "Rio Branco",
    cep: "95010-100",
    emailNfse: "rafael@solucaoadm.com",
    nomeContato: "",
    emailContato: "rafael@solucaoadm.com",
    emailAprovaDemonstrativo: "rafael@solucaoadm.com",
    emailInformaProdutoEmbalado: "rafael@solucaoadm.com",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Solucao",
    diretorioDemonstrativo: "/Demostrativo/Solucao",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Randon S/A Implementos e Participacoes",
    nomeFantasia: "Suspensys",
    nomeInterno: "Suspensys",
    juridica: true,
    cnpjCpf: "89086144000620",
    inscrEstadual: "0290580064",
    inscrMunicipal: "Nulo",
    telefone: "(54)3239-3093",
    logradouro: "Av Abramo Randon",
    numero: "1262",
    complemento: "Anexo B",
    bairro: "Interlagos",
    cep: "95055-010",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Suspensys",
    diretorioDemonstrativo: "/Demostrativo/Randon/Suspensys",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Tabone Industria e Comercio de Plasticos Ltda",
    nomeFantasia: "Tabone - Filial",
    nomeInterno: "Tabone - Filial",
    juridica: true,
    cnpjCpf: "90102609000911",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3026-9559",
    logradouro: "Rua Evaristo De Antoni",
    numero: "3033",
    complemento: "Nulo",
    bairro: "SaoJose",
    cep: "95041-000",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Tabone",
    diretorioDemonstrativo: "/Demostrativo/Tabone",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Tabone Industria e Comercio de Plasticos Ltda",
    nomeFantasia: "Tabone - Matriz",
    nomeInterno: "Tabone - Matriz",
    juridica: true,
    cnpjCpf: "90102609000164",
    inscrEstadual: "0290166489",
    inscrMunicipal: "49694",
    telefone: "(54)3026-9404",
    logradouro: "Rua Gerson Andreis",
    numero: "1110",
    complemento: "Nulo",
    bairro: "Cidade Nova",
    cep: "95112-130",
    emailNfse: "nfe@tabone.com.br;carla.rosa@tabone.com.br;deise.schamrek@tabone.com.br",
    nomeContato: "",
    emailContato: "nfe@tabone.com.br;carla.rosa@tabone.com.br;deise.schamrek@tabone.com.br",
    emailAprovaDemonstrativo: "nfe@tabone.com.br;carla.rosa@tabone.com.br;deise.schamrek@tabone.com.br",
    emailInformaProdutoEmbalado: "nfe@tabone.com.br;carla.rosa@tabone.com.br;deise.schamrek@tabone.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Tabone",
    diretorioDemonstrativo: "/Demostrativo/Tabone",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Imobiliaria Terra e Lar Ltda",
    nomeFantasia: "Terra E Lar",
    nomeInterno: "Terra E Lar",
    juridica: true,
    cnpjCpf: "89087894000102",
    inscrEstadual: "Nulo",
    inscrMunicipal: "23803",
    telefone: "(54)3214-1300",
    logradouro: "Rua Alfredo Chaves",
    numero: "548",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-460",
    emailNfse: "claudia.caixa@terraelar.com.br",
    nomeContato: "",
    emailContato: "claudia.caixa@terraelar.com.br",
    emailAprovaDemonstrativo: "claudia.caixa@terraelar.com.br",
    emailInformaProdutoEmbalado: "claudia.caixa@terraelar.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/TerraeLar",
    diretorioDemonstrativo: "/Demostrativo/TerraeLar",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Fundacao Universidade de Caxias do Sul",
    nomeFantasia: "UCS - Fin",
    nomeInterno: "UCS - Fin",
    juridica: true,
    cnpjCpf: "88648761000103",
    inscrEstadual: "0290089530",
    inscrMunicipal: "Nulo",
    telefone: "(54)3218-2100",
    logradouro: "Rua Francisco Getulio Vargas",
    numero: "1130",
    complemento: "Nulo",
    bairro: "PetrOpolis",
    cep: "95070-560",
    emailNfse: "gcdtelli@ucs.br",
    nomeContato: "",
    emailContato: "gcdtelli@ucs.br",
    emailAprovaDemonstrativo: "gcdtelli@ucs.br",
    emailInformaProdutoEmbalado: "gcdtelli@ucs.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/UCS",
    diretorioDemonstrativo: "/Demostrativo/UCS",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Fundacao Universidade de Caxias do Sul",
    nomeFantasia: "UCS - HG",
    nomeInterno: "UCS - HG",
    juridica: true,
    cnpjCpf: "88648761001843",
    inscrEstadual: "Nulo",
    inscrMunicipal: "62316",
    telefone: "(54)3218-2100",
    logradouro: "Rua Francisco Getulio Vargas",
    numero: "1130",
    complemento: "Nulo",
    bairro: "PetrOpolis",
    cep: "95070-560",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/UCS",
    diretorioDemonstrativo: "/Demostrativo/UCS",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Unimed Nordeste RS Soc. Coop. de Serv. Medicos Ltda",
    nomeFantasia: "Unimed - Medicina",
    nomeInterno: "Unimed - Medicina",
    juridica: true,
    cnpjCpf: "87827689002588",
    inscrEstadual: "Nulo",
    inscrMunicipal: "82103",
    telefone: "(54)3289-9308",
    logradouro: "Rua Sinimbu",
    numero: "1183",
    complemento: "Terreo - Loja B",
    bairro: "Centro",
    cep: "95020-001",
    emailNfse: "nicolle.stecanella@unimednordesters.com.br",
    nomeContato: "",
    emailContato: "nicolle.stecanella@unimednordesters.com.br",
    emailAprovaDemonstrativo: "nicolle.stecanella@unimednordesters.com.br",
    emailInformaProdutoEmbalado: "nicolle.stecanella@unimednordesters.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/UNIMED",
    diretorioDemonstrativo: "/Demostrativo/UNIMED",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Unimed Nordeste RS Soc. Coop. de Serv. Medicos Ltda",
    nomeFantasia: "Unimed",
    nomeInterno: "Unimed",
    juridica: true,
    cnpjCpf: "87827689000100",
    inscrEstadual: "0290331773",
    inscrMunicipal: "16759",
    telefone: "(54)3220-2000",
    logradouro: "Rua Moreira Cesar",
    numero: "2400",
    complemento: "Nulo",
    bairro: "Pio X",
    cep: "95034-000",
    emailNfse: "nfe@unimednordesters.com.br;cartoes@unimednordesters.com.br;caroline.mello@unimednordesters.com.br",
    nomeContato: "",
    emailContato: "nfe@unimednordesters.com.br;cartoes@unimednordesters.com.br;caroline.mello@unimednordesters.com.br",
    emailAprovaDemonstrativo: "nfe@unimednordesters.com.br;cartoes@unimednordesters.com.br;caroline.mello@unimednordesters.com.br",
    emailInformaProdutoEmbalado: "nfe@unimednordesters.com.br;cartoes@unimednordesters.com.br;caroline.mello@unimednordesters.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/UNIMED",
    diretorioDemonstrativo: "/Demostrativo/UNIMED",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Viezzer Eng. e Neg. Imobiliarios Ltda",
    nomeFantasia: "Viezzer",
    nomeInterno: "Viezzer",
    juridica: true,
    cnpjCpf: "89824239000190",
    inscrEstadual: "0290360609",
    inscrMunicipal: "Nulo",
    telefone: "(54)3220-6933",
    logradouro: "Rua Ruben Bento Alves",
    numero: "1419",
    complemento: "Sala 2",
    bairro: "Interlagos",
    cep: "95041-410",
    emailNfse: "nfeletronica@viezzerengenharia.com.br;ivanice@viezzerengenharia.com.br",
    nomeContato: "",
    emailContato: "nfeletronica@viezzerengenharia.com.br;ivanice@viezzerengenharia.com.br",
    emailAprovaDemonstrativo: "nfeletronica@viezzerengenharia.com.br;ivanice@viezzerengenharia.com.br",
    emailInformaProdutoEmbalado: "nfeletronica@viezzerengenharia.com.br;ivanice@viezzerengenharia.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Viezzer",
    diretorioDemonstrativo: "/Demostrativo/Viezzer",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Hidrover Equipamentos Hidraulicos Ltda",
    nomeFantasia: "Hidrover-Weber",
    nomeInterno: "Hidrover-Weber",
    juridica: true,
    cnpjCpf: "88818125000174",
    inscrEstadual: "0480047596",
    inscrMunicipal: "10995",
    telefone: "(54)2992-8812",
    logradouro: "Rod. RS 122 - KM 95",
    numero: "Nulo",
    complemento: "Nulo",
    bairro: "Travessao Garibaldi",
    cep: "95034-500",
    emailNfse: "Joice.Badio@hidrover.com.br;financeiro.brc@hidrover.com.br;nfein@hidrover.com.br",
    nomeContato: "",
    emailContato: "Joice.Badio@hidrover.com.br;financeiro.brc@hidrover.com.br;nfein@hidrover.com.br",
    emailAprovaDemonstrativo: "Joice.Badio@hidrover.com.br;financeiro.brc@hidrover.com.br;nfein@hidrover.com.br",
    emailInformaProdutoEmbalado: "Joice.Badio@hidrover.com.br;financeiro.brc@hidrover.com.br;nfein@hidrover.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Hidrover",
    diretorioDemonstrativo: "/Demostrativo/Hidrover",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Flores da Cunha",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Metalurgica Weloze Ltda",
    nomeFantasia: "Weloze",
    nomeInterno: "Weloze",
    juridica: true,
    cnpjCpf: "87007910000184",
    inscrEstadual: "0290082919",
    inscrMunicipal: "Nulo",
    telefone: "(54)3026-1500",
    logradouro: "Rua Padre AmbrOsio Pieratelli",
    numero: "454",
    complemento: "Nulo",
    bairro: "Kayser",
    cep: "95098-380",
    emailNfse: "nfe@weloze.com.br",
    nomeContato: "",
    emailContato: "nfe@weloze.com.br",
    emailAprovaDemonstrativo: "nfe@weloze.com.br",
    emailInformaProdutoEmbalado: "nfe@weloze.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Weloze",
    diretorioDemonstrativo: "/Demostrativo/Weloze",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Wiretec Ind. de Componentes Eletroeletronicos Ltda",
    nomeFantasia: "Wiretec",
    nomeInterno: "Wiretec",
    juridica: true,
    cnpjCpf: "05319866000183",
    inscrEstadual: "0290399270",
    inscrMunicipal: "79387",
    telefone: "(54)3534-3000",
    logradouro: "Rua Gen. Jacinto Maria de Godoi",
    numero: "2522",
    complemento: "Nulo",
    bairro: "Santa Catarina",
    cep: "95032-140",
    emailNfse: "nfe@wiretec.com.br;rh1@wiretec.com.br",
    nomeContato: "",
    emailContato: "nfe@wiretec.com.br;rh1@wiretec.com.br",
    emailAprovaDemonstrativo: "nfe@wiretec.com.br;rh1@wiretec.com.br",
    emailInformaProdutoEmbalado: "nfe@wiretec.com.br;rh1@wiretec.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Wiretec",
    diretorioDemonstrativo: "/Demostrativo/Wiretec",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Perfilisa Industria de Plasticos de Engenharia Ltda",
    nomeFantasia: "Perfilisa",
    nomeInterno: "Perfilisa",
    juridica: true,
    cnpjCpf: "92097997000168",
    inscrEstadual: "0290165822",
    inscrMunicipal: "49573",
    telefone: "(54)3028-1700",
    logradouro: "Rua Gerson Andreis",
    numero: "636",
    complemento: "Distrito Industrial",
    bairro: "Desvio Rizzo",
    cep: "95112-130",
    emailNfse: "cintiaz@perfilisa.com.br",
    nomeContato: "",
    emailContato: "cintiaz@perfilisa.com.br",
    emailAprovaDemonstrativo: "cintiaz@perfilisa.com.br",
    emailInformaProdutoEmbalado: "cintiaz@perfilisa.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Perfilisa",
    diretorioDemonstrativo: "/Demostrativo/Perfilisa",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Sindicato dos Hospitais e Clinicas de Porto Alegre",
    nomeFantasia: "Sindihospa",
    nomeInterno: "Sindihospa",
    juridica: true,
    cnpjCpf: "92963792000118",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(51)3330-3990",
    logradouro: "Rua Coronel Corte Real",
    numero: "58",
    complemento: "Nulo",
    bairro: "PetrOpolis",
    cep: "90630-080",
    emailNfse: "andreia@sindihospa.com.br",
    nomeContato: "",
    emailContato: "andreia@sindihospa.com.br",
    emailAprovaDemonstrativo: "andreia@sindihospa.com.br",
    emailInformaProdutoEmbalado: "andreia@sindihospa.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Sindihospa",
    diretorioDemonstrativo: "/Demostrativo/Sindihospa",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Porto Alegre",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Hospital Saude Ltda",
    nomeFantasia: "Hospital Saude",
    nomeInterno: "Hospital Saude",
    juridica: true,
    cnpjCpf: "88575394000157",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3026-2699",
    logradouro: "Rua Vinte De Setembro",
    numero: "2311",
    complemento: "Predio",
    bairro: "Centro",
    cep: "95020-450",
    emailNfse: "saudefin@hospitalsaude.com.br;jmsilva@hospitalsaude.com.br",
    nomeContato: "",
    emailContato: "saudefin@hospitalsaude.com.br;jmsilva@hospitalsaude.com.br",
    emailAprovaDemonstrativo: "saudefin@hospitalsaude.com.br;jmsilva@hospitalsaude.com.br",
    emailInformaProdutoEmbalado: "saudefin@hospitalsaude.com.br;jmsilva@hospitalsaude.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/HospSaude",
    diretorioDemonstrativo: "/Demostrativo/HospSaude",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Cia. de Impressao Digital - CTD",
    nomeFantasia: "CTD",
    nomeInterno: "CTD",
    juridica: true,
    cnpjCpf: "93445484000163",
    inscrEstadual: "0240293800",
    inscrMunicipal: "Nulo",
    telefone: "(51)3415-3400",
    logradouro: "Rua Berto Cirio",
    numero: "1450",
    complemento: "Nulo",
    bairro: "SaoLuis",
    cep: "92420-030",
    emailNfse: "acricha@ctd.com.br",
    nomeContato: "",
    emailContato: "acricha@ctd.com.br",
    emailAprovaDemonstrativo: "acricha@ctd.com.br",
    emailInformaProdutoEmbalado: "acricha@ctd.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/CTD",
    diretorioDemonstrativo: "/Demostrativo/CTD",
    prazoPagamento:  14 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Canoas",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Inovacao Negocios Imobiliarios Ltda - ME",
    nomeFantasia: "Inovacao",
    nomeInterno: "Inovacao",
    juridica: true,
    cnpjCpf: "01734687000151",
    inscrEstadual: "Nulo",
    inscrMunicipal: "59526",
    telefone: "(54)3028-6088",
    logradouro: "Rua Alfredo Chaves",
    numero: "1010",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-460",
    emailNfse: "laura@imobiliariainovacao.com.br;financeiro@imobiliariainovacao.com.br",
    nomeContato: "",
    emailContato: "laura@imobiliariainovacao.com.br;financeiro@imobiliariainovacao.com.br",
    emailAprovaDemonstrativo: "laura@imobiliariainovacao.com.br;financeiro@imobiliariainovacao.com.br",
    emailInformaProdutoEmbalado: "laura@imobiliariainovacao.com.br;financeiro@imobiliariainovacao.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Inovacao",
    diretorioDemonstrativo: "/Demostrativo/Inovacao",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Petry Empreendimentos Imobiliarios Ltda - ME",
    nomeFantasia: "SOS",
    nomeInterno: "SOS",
    juridica: true,
    cnpjCpf: "09358728000164",
    inscrEstadual: "Nulo",
    inscrMunicipal: "100387",
    telefone: "(54)3025-1628",
    logradouro: "Rua Os Dezoito do Forte",
    numero: "422",
    complemento: "sala 306",
    bairro: "Lourdes",
    cep: "95020-472",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/SOS",
    diretorioDemonstrativo: "/Demostrativo/SOS",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Lorigraf Grafica e Editora Ltda",
    nomeFantasia: "Lorigraf",
    nomeInterno: "Lorigraf",
    juridica: true,
    cnpjCpf: "93532968000140",
    inscrEstadual: "0290200652",
    inscrMunicipal: "11821",
    telefone: "(54)3021-8400",
    logradouro: "Travessa Sao Marcos",
    numero: "545",
    complemento: "Nulo",
    bairro: "Kayser",
    cep: "95098-490",
    emailNfse: "lorigraf@lorigraf.com.br",
    nomeContato: "",
    emailContato: "lorigraf@lorigraf.com.br",
    emailAprovaDemonstrativo: "lorigraf@lorigraf.com.br",
    emailInformaProdutoEmbalado: "lorigraf@lorigraf.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/GraficaLorigraf",
    diretorioDemonstrativo: "/Demostrativo/GraficaLorigraf",
    prazoPagamento:  21 ,
    tipoFechamento: "IMEDIATO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "15",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Novo Conceito Administradora de Condominios Ltda",
    nomeFantasia: "Novo Conceito",
    nomeInterno: "Novo Conceito",
    juridica: true,
    cnpjCpf: "13868156000130",
    inscrEstadual: "Nulo",
    inscrMunicipal: " NULL",
    telefone: "(54)3039-2908",
    logradouro: "Rua Pinheiro Machado",
    numero: "2569",
    complemento: "Sala 44",
    bairro: "SaoPelegrino",
    cep: "95020-172",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/NovoConceito",
    diretorioDemonstrativo: "/Demostrativo/NovoConceito",
    prazoPagamento:  7 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "America de Antoni Comercio de Confeccoes Ltda",
    nomeFantasia: "Lojas America",
    nomeInterno: "Lojas America",
    juridica: true,
    cnpjCpf: "19020073000769",
    inscrEstadual: "0290",
    inscrMunicipal: "4305108",
    telefone: "(54)3025-2030",
    logradouro: "Av. General Flores Da Cunha",
    numero: "1313",
    complemento: "Nulo",
    bairro: "Vila Imbui",
    cep: "94910-002",
    emailNfse: "Nulo",
    nomeContato: "",
    emailContato: "Nulo",
    emailAprovaDemonstrativo: "Nulo",
    emailInformaProdutoEmbalado: "Nulo",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LojasAmerica",
    diretorioDemonstrativo: "/Demostrativo/LojasAmerica",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Cachoeirinha",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Foca Controles de Acessos Ltda",
    nomeFantasia: "Foca",
    nomeInterno: "Foca",
    juridica: true,
    cnpjCpf: "02451712000152",
    inscrEstadual: "0290322685",
    inscrMunicipal: "63163",
    telefone: "(54)2108-8000",
    logradouro: "Rua Magdalena Aver Fadanelli",
    numero: "1140",
    complemento: "Pavilhao",
    bairro: "Centenario",
    cep: "95045-178",
    emailNfse: "rh@focabraun.com.br",
    nomeContato: "",
    emailContato: "rh@focabraun.com.br",
    emailAprovaDemonstrativo: "rh@focabraun.com.br",
    emailInformaProdutoEmbalado: "rh@focabraun.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Foca",
    diretorioDemonstrativo: "/Demostrativo/Foca",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Intermach Pecas Automotivas Ltda",
    nomeFantasia: "Intermach",
    nomeInterno: "Intermach",
    juridica: true,
    cnpjCpf: "91956755000110",
    inscrEstadual: "0290500443",
    inscrMunicipal: "Nulo",
    telefone: "(54)3013-6400",
    logradouro: "Rua Joao Meneghini",
    numero: "428",
    complemento: "Nulo",
    bairro: "Interlagos",
    cep: "95055-330",
    emailNfse: "nfe@intermach.ind.br;rh02@intermach.ind.br",
    nomeContato: "",
    emailContato: "nfe@intermach.ind.br;rh02@intermach.ind.br",
    emailAprovaDemonstrativo: "nfe@intermach.ind.br;rh02@intermach.ind.br",
    emailInformaProdutoEmbalado: "nfe@intermach.ind.br;rh02@intermach.ind.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Intermach",
    diretorioDemonstrativo: "/Demostrativo/Intermach",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Jobel Engenharia Ltda",
    nomeFantasia: "Jobel",
    nomeInterno: "Jobel",
    juridica: true,
    cnpjCpf: "88584511000149",
    inscrEstadual: "0290354919",
    inscrMunicipal: "20163",
    telefone: "(54)3536-4600",
    logradouro: "Rua Marechal Floriano",
    numero: "1567",
    complemento: "Nulo",
    bairro: "Centro",
    cep: "95020-372",
    emailNfse: "nfe@jobel.com.br;daniele@jobel.com.br;rosalba@jobel.com.br",
    nomeContato: "",
    emailContato: "nfe@jobel.com.br;daniele@jobel.com.br;rosalba@jobel.com.br",
    emailAprovaDemonstrativo: "nfe@jobel.com.br;daniele@jobel.com.br;rosalba@jobel.com.br",
    emailInformaProdutoEmbalado: "nfe@jobel.com.br;daniele@jobel.com.br;rosalba@jobel.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Jobel",
    diretorioDemonstrativo: "/Demostrativo/Jobel",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "PERMUNDY - Gestao de Condominios Ltda",
    nomeFantasia: "Imperia",
    nomeInterno: "Imperia",
    juridica: true,
    cnpjCpf: "17261092000166",
    inscrEstadual: "Nulo",
    inscrMunicipal: "130276",
    telefone: "(54)3025-8665",
    logradouro: "Rua Sinimbu",
    numero: "2091",
    complemento: "Salas 116 e 118",
    bairro: "Centro",
    cep: "95020-002",
    emailNfse: "financeiro@imperiacondominios.com.br",
    nomeContato: "",
    emailContato: "financeiro@imperiacondominios.com.br",
    emailAprovaDemonstrativo: "financeiro@imperiacondominios.com.br",
    emailInformaProdutoEmbalado: "financeiro@imperiacondominios.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Imperia",
    diretorioDemonstrativo: "/Demostrativo/Imperia",
    prazoPagamento:  14 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Avivra Administradora de Condominios Ltda",
    nomeFantasia: "Avivra",
    nomeInterno: "Avivra",
    juridica: true,
    cnpjCpf: "20486885000198",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3268-7741",
    logradouro: "Rua Ruy Barbosa",
    numero: "20",
    complemento: "A - Sala 706",
    bairro: "Centro",
    cep: "95170-440",
    emailNfse: "contato@avivra.com.br;marcos@avivra.com.br",
    nomeContato: "",
    emailContato: "contato@avivra.com.br;marcos@avivra.com.br",
    emailAprovaDemonstrativo: "contato@avivra.com.br;marcos@avivra.com.br",
    emailInformaProdutoEmbalado: "contato@avivra.com.br;marcos@avivra.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Avivra",
    diretorioDemonstrativo: "/Demostrativo/Avivra",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Mercosul Indústria de Motores Ltda",
    nomeFantasia: "EBERLE",
    nomeInterno: "EBERLE",
    juridica: true,
    cnpjCpf: "15568388000107",
    inscrEstadual: "0290557321",
    inscrMunicipal: "Nulo",
    telefone: "(54)3026-3400",
    logradouro: "Estrada Federal BR-116 - Km 145",
    numero: "5000",
    complemento: "Nulo",
    bairro: "Sao Cristovao",
    cep: "95059-520",
    emailNfse: "maiara.souza@mercosulmotores.com.br;kamila.rosa@mercosulmotores.com.br",
    nomeContato: "",
    emailContato: "maiara.souza@mercosulmotores.com.br;kamila.rosa@mercosulmotores.com.br",
    emailAprovaDemonstrativo: "maiara.souza@mercosulmotores.com.br;kamila.rosa@mercosulmotores.com.br",
    emailInformaProdutoEmbalado: "maiara.souza@mercosulmotores.com.br;kamila.rosa@mercosulmotores.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Eberle",
    diretorioDemonstrativo: "/Demostrativo/Eberle",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Habil Condominios LTDA",
    nomeFantasia: "Habil",
    nomeInterno: "Habil",
    juridica: true,
    cnpjCpf: "24107215000174",
    inscrEstadual: "Nulo",
    inscrMunicipal: "Nulo",
    telefone: "(54)3536-6718",
    logradouro: "Rua Vinte de Setembro",
    numero: "1675",
    complemento: "Sala 302",
    bairro: "Centro",
    cep: "95020-450",
    emailNfse: "habilcondominios@habilcondominios.com.br",
    nomeContato: "",
    emailContato: "habilcondominios@habilcondominios.com.br",
    emailAprovaDemonstrativo: "habilcondominios@habilcondominios.com.br",
    emailInformaProdutoEmbalado: "habilcondominios@habilcondominios.com.br",
    tipoFaturamento: "R" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Habil",
    diretorioDemonstrativo: "/Demostrativo/Habil",
    prazoPagamento:  7 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Frost Frio Refrigeracao Industrial SA",
    nomeFantasia: "Frost Frio",
    nomeInterno: "Frost Frio",
    juridica: true,
    cnpjCpf: "02210803000104",
    inscrEstadual: "0290318645",
    inscrMunicipal: "114477",
    telefone: "(54)3220-8149",
    logradouro: "Rua Hermes Fontes",
    numero: "365",
    complemento: "Nulo",
    bairro: "Santa Fe",
    cep: "95045-180",
    emailNfse: "natalise.zanin@guentner.com;nfef@guentner.com",
    nomeContato: "",
    emailContato: "natalise.zanin@guentner.com;nfef@guentner.com",
    emailAprovaDemonstrativo: "natalise.zanin@guentner.com;nfef@guentner.com",
    emailInformaProdutoEmbalado: "natalise.zanin@guentner.com;nfef@guentner.com",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Frost",
    diretorioDemonstrativo: "/Demostrativo/Frost",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Guntner do Brasil Representacoes Ltda",
    nomeFantasia: "Guntner",
    nomeInterno: "Guntner",
    juridica: true,
    cnpjCpf: "10417549000130",
    inscrEstadual: "0290498376",
    inscrMunicipal: "Nulo",
    telefone: "(54)3220-8149",
    logradouro: "Rua Hermes Fontes",
    numero: "365",
    complemento: "Sala 2",
    bairro: "Santa Fe",
    cep: "95045-180",
    emailNfse: "clarice.rech@guentner.com",
    nomeContato: "",
    emailContato: "clarice.rech@guentner.com",
    emailAprovaDemonstrativo: "clarice.rech@guentner.com",
    emailInformaProdutoEmbalado: "clarice.rech@guentner.com",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Frost",
    diretorioDemonstrativo: "/Demostrativo/Frost",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "CeA Comercio de Alimentos Ltda",
    nomeFantasia: "SUPER CRISAN",
    nomeInterno: "SUPER CRISAN",
    juridica: true,
    cnpjCpf: "06348488000129",
    inscrEstadual: "0290424712",
    inscrMunicipal: "84287",
    telefone: "(54)3217-7119",
    logradouro: "Professora Nely Veronese Macia",
    numero: "714",
    complemento: "Nulo",
    bairro: "Esplanada",
    cep: "95095-281",
    emailNfse: "lucianecrisan@yahoo.com.br",
    nomeContato: "",
    emailContato: "lucianecrisan@yahoo.com.br",
    emailAprovaDemonstrativo: "lucianecrisan@yahoo.com.br",
    emailInformaProdutoEmbalado: "lucianecrisan@yahoo.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/CRISAN",
    diretorioDemonstrativo: "/Demostrativo/CRISAN",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Lamina Industria Plastica Ltda",
    nomeFantasia: "Lamina",
    nomeInterno: "Lamina",
    juridica: true,
    cnpjCpf: "05853030000164",
    inscrEstadual: "0290412285",
    inscrMunicipal: "Nulo",
    telefone: "(54)3217-9099",
    logradouro: "Rod RSC 453",
    numero: "16401",
    complemento: "Setor F",
    bairro: "Santa Fé",
    cep: "95045-630",
    emailNfse: "nfe.lamina@lamina.ind.br;rh2@lamina.ind.br;rh@lamina.ind.br",
    nomeContato: "",
    emailContato: "nfe.lamina@lamina.ind.br;rh2@lamina.ind.br;rh@lamina.ind.br",
    emailAprovaDemonstrativo: "nfe.lamina@lamina.ind.br;rh2@lamina.ind.br;rh@lamina.ind.br",
    emailInformaProdutoEmbalado: "nfe.lamina@lamina.ind.br;rh2@lamina.ind.br;rh@lamina.ind.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Lamina",
    diretorioDemonstrativo: "/Demostrativo/Lamina",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Espumatec Industria e Comercio de Componentes em Poliuretano Ltda",
    nomeFantasia: "Espumatc",
    nomeInterno: "Espumatc",
    juridica: true,
    cnpjCpf: "17340782000100",
    inscrEstadual: "0290621836",
    inscrMunicipal: "130002",
    telefone: "(54)3209-6500",
    logradouro: "Rua Honorato Bazei",
    numero: "150",
    complemento: "Nulo",
    bairro: "Cidade Nova",
    cep: "95112-140",
    emailNfse: "rh1@espumatec.com.br;compras2@espumatec.com.br",
    nomeContato: "",
    emailContato: "rh1@espumatec.com.br;compras2@espumatec.com.br",
    emailAprovaDemonstrativo: "rh1@espumatec.com.br;compras2@espumatec.com.br",
    emailInformaProdutoEmbalado: "rh1@espumatec.com.br;compras2@espumatec.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Espumatec",
    diretorioDemonstrativo: "/Demostrativo/Espumatec",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR_OU_PRAZO" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "AGROSUL Agroavicola Industrial S/A",
    nomeFantasia: "Agrosul",
    nomeInterno: "Agrosul",
    juridica: true,
    cnpjCpf: "88369889000634",
    inscrEstadual: "1280044087",
    inscrMunicipal: "Nulo",
    telefone: "(51)3635-6700",
    logradouro: "Rua Waldomiro Freiberger",
    numero: "1000",
    complemento: "Nulo",
    bairro: "Camprestre",
    cep: "95760-000",
    emailNfse: "financeiro@agrosul.com.br;nf-e@agrosul.com.br;grupo.contabilidade@agrosul.com.br;dione.junges@agrosul.com.br",
    nomeContato: "",
    emailContato: "financeiro@agrosul.com.br;nf-e@agrosul.com.br;grupo.contabilidade@agrosul.com.br;dione.junges@agrosul.com.br",
    emailAprovaDemonstrativo: "financeiro@agrosul.com.br;nf-e@agrosul.com.br;grupo.contabilidade@agrosul.com.br;dione.junges@agrosul.com.br",
    emailInformaProdutoEmbalado: "financeiro@agrosul.com.br;nf-e@agrosul.com.br;grupo.contabilidade@agrosul.com.br;dione.junges@agrosul.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Agrosul",
    diretorioDemonstrativo: "/Demostrativo/Agrosul",
    prazoPagamento:  14 ,
    tipoFechamento: "MENSAL_FIXO" as const,
    valorAlvo: "0",
    valorMinimo: "0",
    prazoMaximoDias: 0,
    diaFechamento: "Último",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "São Sebastião do Caí",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "America De Antoni Comercio de Confeccoes Ltda",
    nomeFantasia: "Lojas America MTZ",
    nomeInterno: "Lojas America MTZ",
    juridica: true,
    cnpjCpf: "19020073000173",
    inscrEstadual: "0290580439",
    inscrMunicipal: "Nulo",
    telefone: "(51)3393-2800",
    logradouro: "Rua Bento Gonçalves",
    numero: "950",
    complemento: "Sala 02 - B",
    bairro: "Centro",
    cep: "95020-411",
    emailNfse: "aline@lojasamerica.com.br",
    nomeContato: "",
    emailContato: "aline@lojasamerica.com.br",
    emailAprovaDemonstrativo: "aline@lojasamerica.com.br",
    emailInformaProdutoEmbalado: "aline@lojasamerica.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/LojasAmerica",
    diretorioDemonstrativo: "/Demostrativo/LojasAmerica",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Caxias do Sul",
    municipioUF: "RS",
  },
  {
    nomeRazaoSocial: "Randon TRIEL HT Implementos Rod.",
    nomeFantasia: "TRIELHT",
    nomeInterno: "TRIELHT",
    juridica: true,
    cnpjCpf: "33204183000116",
    inscrEstadual: "0390182214",
    inscrMunicipal: "Nulo",
    telefone: "(54)3520-1100",
    logradouro: "ÁREA RURAL",
    numero: "600",
    complemento: "Nulo",
    bairro: "Nulo",
    cep: "99714-899",
    emailNfse: "fiscal.nfservicos@empresasrandon.com.br",
    nomeContato: "",
    emailContato: "fiscal.nfservicos@empresasrandon.com.br",
    emailAprovaDemonstrativo: "fiscal.nfservicos@empresasrandon.com.br",
    emailInformaProdutoEmbalado: "fiscal.nfservicos@empresasrandon.com.br",
    tipoFaturamento: "N" as const,
    emiteBoleto: true,
    exigeDemonstrativo: true,
    pedidoCompra: false,
    diretorioProducao: "/Randon/Triel",
    diretorioDemonstrativo: "/Demostrativo/Randon/Triel",
    prazoPagamento:  14 ,
    tipoFechamento: "POR_VALOR" as const,
    valorAlvo: "100",
    valorMinimo: "50",
    prazoMaximoDias: 60,
    diaFechamento: "7",
    fecharAoDisponibilizar: false,
    ativo: true,
    municipioNome: "Erechim",
    municipioUF: "RS",
  },
];

async function seed() {
  for (const { municipioNome, municipioUF, ...cliente } of clientes) {
    const municipioId = await getMunicipioId(municipioNome, municipioUF);
    if (!municipioId) {
      console.warn(`Município não encontrado: ${municipioNome}/${municipioUF}. Execute seed:municipios primeiro.`);
    }

    const data = { ...cliente, municipioId };

    const keyClause = cliente.cnpjCpf
      ? eq(clientesTable.cnpjCpf, cliente.cnpjCpf)
      : cliente.nomeInterno
        ? eq(clientesTable.nomeInterno, cliente.nomeInterno)
        : null;

    if (!keyClause) {
      console.log(`Ignorado (sem chave Ãºnica): ${cliente.nomeRazaoSocial}`);
      continue;
    }

    const [existing] = await db
      .select({ id: clientesTable.id })
      .from(clientesTable)
      .where(keyClause)
      .limit(1);

    if (existing) {
      await db.update(clientesTable).set(data).where(eq(clientesTable.id, existing.id));
      console.log(`Atualizado: ${cliente.nomeRazaoSocial} (id=${existing.id})`);
    } else {
      const [inserted] = await db
        .insert(clientesTable)
        .values(data)
        .returning({ id: clientesTable.id });
      console.log(`Inserido: ${cliente.nomeRazaoSocial} (id=${inserted.id})`);
    }
  }

  console.log("Seed de clientes concluído.");
  process.exit(0);
}

seed().catch((err) => {
  console.error(err);
  process.exit(1);
});